### ISSUE TITLE
No cli option for disabling the generation of check dependencies

### ISSUE THREAD

**Issue by datakurre** [datakurre/pip2nix#16]
> We really don't want the test packages in this case as it makes our build really big. We might just end up with a fork to handle that case then.

**Comment by datakurre** [comment]
@marcinkuzminski At https://github.com/datakurre/pip2nix/issues/9 you reported that pip2nix includes packages' test dependencies in the results.

Would you be able to provide an example of a package that causes this to happen?

For me it seems that resolving of test dependencies is still broken / completely missing. Just by trying a few popular packages, I was not able to find a package that caused result to include it tests dependencies.

**Comment by marcinkuzminski** [comment]
You mean checkInputs where always empty? We had *most* of the packages add checkInputs when generating non-wheel source packages.

**Comment by datakurre** [comment]
@marcinkuzminski Ok. Possibly there are some differences between pip versions.

I guess, I should try to reproduce with different nixpkgs versions.

**Comment by datakurre** [comment]
I still have no idea, how I manage use pip2nix myself so that it does not generate checkInputs. While debugging my project without and the other project with checkInputs, all configuration looked the same, all package versions were the same and still the other build had tests_requires.txt generated by pip for checkInputs and the other project did not. Possibly something related to pip and environment variables.
